[project]
name = "discordbot"
version = "0.1.0"
description = "Simple discord bot with autoresponder capabilities."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord.py",
    "aiosqlite",
]
